pangolin_reset_database:
    path:  /cmd/db-restart
    controller: Geeks\Pangolin\Controller\ResetDatabaseController::index

pangolin_logs:
    path: /cmd/get-db-changes

    controller: Geeks\Pangolin\Controller\LogController::index