#
services:

  doctrine.dbal.logger:
    class: Geeks\Pangolin\Logger\SimpleLogger
    arguments: ['@doctrine.orm.entity_manager']

  Geeks\Pangolin\Controller\ResetDatabaseController:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true
    public: true
    calls:
      - method: setContainer
        arguments: [ '@service_container' ]

  Geeks\Pangolin\Controller\LogController:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true
    public: true
    calls:
      - method: setContainer
        arguments: [ '@service_container' ]

  Geeks\Pangolin\Controller\SqlExecutionController:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true
    public: true
    calls:
      - method: setContainer
        arguments: [ '@service_container' ]
